Create working version of doprg

diff --git a/doprg b/doprg
--- a/doprg
+++ b/doprg
@@ -1,46 +1,95 @@
 #!/bin/bash
 
 # const
-NAME="doprg"
+NAME='doprg'
+declare -A CMD_COMP=(
+	['java']="javac -d %1 %2"
+	['c']="gcc -o %1/\$(rmext \$(basename %2)) %2"
+	['python']="true"
+)
+declare -A CMD_RUN=(
+	['java']="java -classpath %1 \$(rmext %2)"
+	['c']="%1/\$(rmext \$(basename %2))"
+	['python']="python %2"
+)
 
-# flag
-nocomp=0
+# flag, opt
+norun=0
+input=''
+output=$(mktemp -d /tmp/doprg-XXXXXX)
+outtmp=1
 
-function helpmsg() {
+# func
+function helpmsg() { # echo help
 	cat <<EOS
 Usage: $NAME [options] <file>
 
 Options:
-	-n		: Compiling only; do not run
-	-h		: Show this help
+	-o, --output=FILE   : the compiled file will be saved to FILE
+	-n, --norun         : compiling only; the output will be saved in current directory or specified by -o
+	-h, --help          : show this help
 
-About:
-$NAME, my-tools-sh by yuu528
+About: $NAME, my-tools-sh by yuu528
 EOS
 }
 
-function compilemsg() {
-	echo "Detected language: $1"
-	echo "Compiling..."
+function endscript() { # exit with cleaning up temp file, args: exit code
+	[ $outtmp -eq 1 ] && rm -r $output
+	exit $1
 }
 
-while getopts "h" opt; do
-	case $opt in
-		n) nocomp=1;;
-		h) helpmsg;;
-		*) echo -e "$NAME: invalid option -- '$opt'\nTry '$NAME -h' for more information."; exit 1;;
+function run() { # compile and run, args: language
+	if ! eval $(echo ${CMD_COMP[$1]} | sed -e "s#%1#$output#g" -e "s#%2#$input#g"); then
+		echo 'Compiling failed.'
+		endscript 1
+	fi
+	echo 'Compiling completed.'
+
+	if [ $norun -eq 0 ]; then
+		echo 'Running...'
+		eval $(echo ${CMD_RUN[$1]} | sed -e "s#%1#$output#g" -e "s#%2#$input#g")
+	fi
+}
+
+function rmext() { # remove extention from filename, args: filename
+	echo $1 | sed 's/\..\+$//'
+}
+
+# main
+# parse options
+ARGS=$(getopt -o 'o:nh' -l 'output:,norun,help' -- "$@") || endscript 1
+eval "set -- $ARGS"
+
+while [ $# -gt 0 ]; do
+	case $1 in
+		-o | --output) rmdir $output; outtmp=0; output=$(realpath "$2"); shift 2;;
+		-n | --norun) norun=1; shift;;
+		-h | --help) helpmsg; endscript 0;;
+		--) shift; break;;
 	esac
 done
 
-shift $(($OPTIND - 1))
-
-[ -z "$1" ] && echo "$NAME: missing file operand."; exit 1
-[ ! -f "$1" ] && echo "$NAME: cannot access '$1'; No such file."; exit 1
+# check input file
+if [ -z "$1" ]; then
+	echo "$NAME: missing file operand."
+	endscript 1
+elif [ "$1" = "-" ]; then
+	# read input from stdin
+	input='/dev/stdin'
+elif [ ! -f "$1" ]; then
+	echo "$NAME: cannot access '$1'; No such file."
+	endscript 1
+else
+	input="$1"
+fi
 
 # language detection from extention
 ext=$(echo $(basename $1) | sed 's/^.*\.\([^\.]*\)$/\1/')
 
 case $ext in
-	"java")
-		compilemsg Java;;
+	'java') run 'java';;
+	'c') run 'c';;
+	'py') run 'python';;
 esac
+
+endscript 0
